-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 19:20:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imobiliaria` DEFAULT CHARACTER SET utf8 ;
USE `imobiliaria` ;

-- -----------------------------------------------------
-- Table `imobiliaria`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`pessoa` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `estado_civil` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`funcionario_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`funcionario_cargo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  `salario_base` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`usuario` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(15) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`funcionario` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data_ingresso` DATE NOT NULL,
  `salario_real` DECIMAL NOT NULL,
  `codigo_cargo_funcionario` INT NOT NULL,
  `codigo_pessoa` INT NOT NULL,
  `codigo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo`, `codigo_pessoa`),
  INDEX `fk_funcionario_funcionario_cargo1_idx` (`codigo_cargo_funcionario` ASC) VISIBLE,
  INDEX `fk_funcionario_pessoa1_idx` (`codigo_pessoa` ASC) VISIBLE,
  INDEX `fk_funcionario_usuario1_idx` (`codigo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_funcionario_cargo1`
    FOREIGN KEY (`codigo_cargo_funcionario`)
    REFERENCES `imobiliaria`.`funcionario_cargo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pessoa1`
    FOREIGN KEY (`codigo_pessoa`)
    REFERENCES `imobiliaria`.`pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `imobiliaria`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`cliente` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `profissao` VARCHAR(100) NOT NULL,
  `tipo_cliente` CHAR(3) NOT NULL,
  `codigo_pessoa` INT NOT NULL,
  PRIMARY KEY (`codigo`, `codigo_pessoa`),
  INDEX `fk_cliente_pessoa1_idx` (`codigo_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`codigo_pessoa`)
    REFERENCES `imobiliaria`.`pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `tipo_oferta` CHAR(2) NOT NULL,
  `data_construcao` DATE NOT NULL,
  `data_disponivel` DATE NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `valor_sugerido` DECIMAL(15,2) NOT NULL,
  `tipo_imovel` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel_proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel_proprietario` (
  `codigo_cliente` INT NOT NULL,
  `codigo_imovel` INT NOT NULL,
  INDEX `fk_cliente_has_imovel_imovel1_idx` (`codigo_imovel` ASC) VISIBLE,
  INDEX `fk_cliente_has_imovel_cliente1_idx` (`codigo_cliente` ASC) VISIBLE,
  PRIMARY KEY (`codigo_imovel`, `codigo_cliente`),
  CONSTRAINT `fk_cliente_has_imovel_cliente1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `imobiliaria`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_imovel_imovel1`
    FOREIGN KEY (`codigo_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel_terreno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel_terreno` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `area` DECIMAL(15,3) NOT NULL,
  `largura` DECIMAL(15,3) NOT NULL,
  `comprimento` DECIMAL(15,3) NOT NULL,
  `aclive_declive` CHAR(1) NOT NULL,
  `imovel_terrenocol` VARCHAR(45) NOT NULL,
  `codigo_imovel` INT NOT NULL,
  PRIMARY KEY (`codigo`, `codigo_imovel`),
  INDEX `fk_imovel_terreno_imovel1_idx` (`codigo_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_terreno_imovel1`
    FOREIGN KEY (`codigo_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel_casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel_casa` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `qtd_quartos` INT NOT NULL,
  `qtd_suites` INT NOT NULL,
  `qtd_sala_estar` INT NOT NULL,
  `qtd_sala_jantar` INT NOT NULL,
  `num_vagas` INT NOT NULL,
  `area` DECIMAL(15,3) NOT NULL,
  `armario_embutido` TINYINT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `imovel_casacol` VARCHAR(45) NOT NULL,
  `codigo_imovel` INT NOT NULL,
  PRIMARY KEY (`codigo`, `codigo_imovel`),
  INDEX `fk_imovel_casa_imovel1_idx` (`codigo_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_casa_imovel1`
    FOREIGN KEY (`codigo_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel_casa_apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel_casa_apartamento` (
  `codigo_imovel_casa` INT NOT NULL AUTO_INCREMENT,
  `codigo_imovel_casa_imovel` INT NOT NULL,
  `andar` INT NOT NULL,
  `taxa_condominio` DECIMAL(15,2) NOT NULL,
  `portaria24h` TINYINT NOT NULL,
  PRIMARY KEY (`codigo_imovel_casa`, `codigo_imovel_casa_imovel`),
  CONSTRAINT `fk_imovel_casa_apartamento_imovel_casa1`
    FOREIGN KEY (`codigo_imovel_casa` , `codigo_imovel_casa_imovel`)
    REFERENCES `imobiliaria`.`imovel_casa` (`codigo` , `codigo_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel_sala_comercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel_sala_comercial` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `area` DECIMAL(15,3) NOT NULL,
  `qtd_banheiro` INT NOT NULL,
  `qtd_comodo` INT NOT NULL,
  `imovel_sala_comercialcol` VARCHAR(45) NOT NULL,
  `codigo_imovel` INT NOT NULL,
  PRIMARY KEY (`codigo`, `codigo_imovel`),
  INDEX `fk_imovel_sala_comercial_imovel1_idx` (`codigo_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_sala_comercial_imovel1`
    FOREIGN KEY (`codigo_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`forma_pagamento` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`transacao` (
  `num_contrato` INT NOT NULL AUTO_INCREMENT,
  `valor_acordado` DECIMAL(15,2) NOT NULL,
  `comissao_imobiliaria` DECIMAL(15,2) NOT NULL,
  `comissao_funcionario` DECIMAL(15,2) NOT NULL,
  `data_transacao` DATE NOT NULL,
  `codigo_funcionario` INT NOT NULL,
  `codigo_cliente` INT NOT NULL,
  `codigo_forma_pagamento` INT NOT NULL,
  `codigo_imovel` INT NOT NULL,
  PRIMARY KEY (`num_contrato`),
  INDEX `fk_transacao_funcionario1_idx` (`codigo_funcionario` ASC) VISIBLE,
  INDEX `fk_transacao_cliente1_idx` (`codigo_cliente` ASC) VISIBLE,
  INDEX `fk_transacao_forma_pagamento1_idx` (`codigo_forma_pagamento` ASC) VISIBLE,
  INDEX `fk_transacao_imovel1_idx` (`codigo_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_transacao_funcionario1`
    FOREIGN KEY (`codigo_funcionario`)
    REFERENCES `imobiliaria`.`funcionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_cliente1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `imobiliaria`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_forma_pagamento1`
    FOREIGN KEY (`codigo_forma_pagamento`)
    REFERENCES `imobiliaria`.`forma_pagamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_imovel1`
    FOREIGN KEY (`codigo_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`historico` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `num_contrato` INT NOT NULL,
  `valor_acordado` DECIMAL(15,2) NOT NULL,
  `comissao_imobiliaria` DECIMAL(15,2) NOT NULL,
  `comissao_funcionario` DECIMAL(15,2) NOT NULL,
  `data_transacao` DATE NOT NULL,
  `imovel_codigo` INT NOT NULL,
  `cliente_codigo` INT NOT NULL,
  `funcionario_codigo` INT NOT NULL,
  `proprietario_codigo` VARCHAR(45) NOT NULL,
  `tipo_imovel` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`transacao_fiador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`transacao_fiador` (
  `codigo_pessoa` INT NOT NULL,
  `transacao_num_contrato` INT NOT NULL,
  PRIMARY KEY (`codigo_pessoa`, `transacao_num_contrato`),
  INDEX `fk_transacao_has_pessoa_pessoa1_idx` (`codigo_pessoa` ASC) VISIBLE,
  INDEX `fk_transacao_fiador_transacao1_idx` (`transacao_num_contrato` ASC) VISIBLE,
  CONSTRAINT `fk_transacao_has_pessoa_pessoa1`
    FOREIGN KEY (`codigo_pessoa`)
    REFERENCES `imobiliaria`.`pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_fiador_transacao1`
    FOREIGN KEY (`transacao_num_contrato`)
    REFERENCES `imobiliaria`.`transacao` (`num_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`indicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`indicacao` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`indacacao_transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`indacacao_transacao` (
  `codigo_indicacao` INT NOT NULL,
  `transacao_num_contrato` INT NOT NULL,
  PRIMARY KEY (`codigo_indicacao`, `transacao_num_contrato`),
  INDEX `fk_indicacao_has_transacao_transacao1_idx` (`transacao_num_contrato` ASC) VISIBLE,
  INDEX `fk_indicacao_has_transacao_indicacao1_idx` (`codigo_indicacao` ASC) VISIBLE,
  CONSTRAINT `fk_indicacao_has_transacao_indicacao1`
    FOREIGN KEY (`codigo_indicacao`)
    REFERENCES `imobiliaria`.`indicacao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicacao_has_transacao_transacao1`
    FOREIGN KEY (`transacao_num_contrato`)
    REFERENCES `imobiliaria`.`transacao` (`num_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel_foto` (
  `idimovel_foto` INT NOT NULL,
  `foto` MEDIUMBLOB NOT NULL,
  `codigo_imovel` INT NOT NULL,
  PRIMARY KEY (`idimovel_foto`, `codigo_imovel`),
  INDEX `fk_imovel_foto_imovel1_idx` (`codigo_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_foto_imovel1`
    FOREIGN KEY (`codigo_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
